apiVersion: apps/v1
kind: Deployment
metadata:
  name: amansdlc-deployment
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: amanpatelofficial/amanops:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-app-svc
spec:
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 80        # Cluster-facing port
    targetPort: 80  # Container port
    nodePort: 30080 # Optional: fixed port on the node, else Kubernetes assigns one in the range 30000-32767
  type: NodePort     # Expose service externally via <NodeIP>:<NodePort>
