apiVersion: apps/v1
kind: Deployment
metadata:
  name: amansdlc-deployment
  labels:
    app: devops-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-portfolio
  template:
    metadata:
      labels:
        app: devops-portfolio
    spec:
      containers:
      - name: devops-portfolio
        image: amanpatelofficial/devops-portfolio:tagname:v1.0.1
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: devops-portfolio-svc
spec:
  selector:
    app: devops-portfolio
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-portfolio-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:123456789012:certificate/your-certificate-id
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-port: "80"
spec:
  rules:
  - host: amansdlc.com   # Replace with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-portfolio-svc
            port:
              number: 80
