name: Let's Code & Deploy

on:
  push:
    branches:
      - main

jobs:
  checkout:
    name: Checkout Code
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.set_image.outputs.image_name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Image Name
        id: set_image
        run: echo "image_name=${{ secrets.DOCKER_HUB_USERNAME }}/amanops:latest" >> $GITHUB_OUTPUT

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/amanops:latest
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  scan:
    name: Scan Image with Trivy
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Scan Docker Image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/amanops:latest
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image $IMAGE_NAME | tee trivy-report.log

  whitelist:
    name: Whitelist GitHub Actions IP
    runs-on: ubuntu-latest
    needs: scan
    outputs:
      runner_ip: ${{ steps.get_ip.outputs.runner_ip }}
    steps:
      - name: Whitelist IP in AWS Security Group
        id: get_ip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SECURITY_GROUP_ID: ${{ secrets.SECURITY_GROUP_ID }}
        run: |
          RUNNER_IP=$(curl -s https://checkip.amazonaws.com)
          echo "runner_ip=$RUNNER_IP" >> $GITHUB_OUTPUT
          aws ec2 authorize-security-group-ingress \
            --group-id $SECURITY_GROUP_ID \
            --protocol tcp \
            --port 22 \
            --cidr $RUNNER_IP/32 \
            --region $AWS_REGION

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: whitelist
    steps:
      - name: SSH and Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
          IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/amanops:latest
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -tt -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << EOF
            set -x
            sudo docker stop my-app || true
            sudo docker system prune -af
            sudo docker pull $IMAGE_NAME
            sudo docker run -d --restart=always --name my-app -p 8080:80 $IMAGE_NAME
          EOF
          rm -f private_key.pem

  revoke:
    name: Revoke GitHub Actions Public IP
    runs-on: ubuntu-latest
    if: always()
    needs: [deploy, whitelist]
    steps:
      - name: Remove Runner IP from Security Group
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SECURITY_GROUP_ID: ${{ secrets.SECURITY_GROUP_ID }}
          RUNNER_IP: ${{ needs.whitelist.outputs.runner_ip }}
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id $SECURITY_GROUP_ID \
            --protocol tcp \
            --port 22 \
            --cidr $RUNNER_IP/32 \
            --region $AWS_REGION
